[package]
name = "boids"
version = "0.1.0"
authors = ["gzordrai <40698142+gzordrai@users.noreply.github.com>"]
edition = "2021"

[dependencies]
macroquad = "0.4.14"
once_cell = "1.21.3"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.8.23"
